theme = "solarized-dark"
icons = "awesome5"


[[block]]
block = "memory"
display_type = "memory"
format_mem = "{MUp}%/{MTg}GB"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "disk_space"
path = "/"
alias = ""
info_type = "available"
unit = "GB"
interval = 60
warning = 20.0
alert = 10.0

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "%A %d/%h/%Y %T"